name: AutoGreen-CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: "0 */6 * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set user info
        run: |
          git config --global user.email "${{ github.email }}"
          git config --global user.name "${{ github.actor }}"

      - name: Create and update README.md
        run: |
          echo "## Contributions" > README.md
          echo "Last updated: $(date '+%Y-%m-%d %H:%M:%S %Z')" >> README.md
          echo "Total commits: $(( $(git rev-list --count HEAD) + 1 ))" >> README.md
          
          git add README.md
          git commit -m "a commit a day keeps your girlfriend away" --allow-empty
          git push
