name: AutoGreen-CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: "0 */6 * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set user info
        run: |
          git config --global user.email "${{ github.email }}"
          git config --global user.name "${{ github.actor }}"
          git fetch
          git checkout master

      - name: update README.md
        run: |
          echo "## AutoGreen" > README.md
          echo "Last updated: $(date +'%Y-%m-%d %H:%M:%S %Z')\n" >> README.md
          echo "Commits: ${{ github.event.repository.commits_count }}\n" >> README.md
          echo "Timezone: Beijing Time (UTC+8)\n" >> README.md

      - name: |
          git add README.md
          git commit -m "a commit a day keeps your girlfriend away" --allow-empty
          git push origin master
