name: Update Contributions

on:
  schedule:
    - cron: "0 0 * * *"  # 每天凌晨 00:00 UTC 执行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run update script
      run: |
        chmod +x update_contributions.sh
        ./update_contributions.sh
