name: Update Contributions

on:
  schedule:
    - cron: "2 */3 * * *"  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run update script
      run: |
        chmod +x linux_autoGreen.sh
        ./linux_autoGreen.sh
